import { Marked, type Tokens } from 'marked'

// Menu order. Titles come from each file's H1, never from a parallel list here.
// The technical group is written for whoever maintains the code, not for the
// people using the platform, so it stays visually separate from the guide.
// tech-* pages are generated by backend/scripts/gen_tech_docs.py.
export const DOC_GROUPS = [
  {
    key: 'docs.group.guide',
    slugs: [
      'secret-rotation',
      'connect-account',
      'account-errors',
      'manage-users',
      'email-reports',
      'dashboard-guide',
      'known-limits',
    ],
  },
  {
    key: 'docs.group.technical',
    slugs: [
      'tech-architecture',
      'tech-scheduler',
      'tech-data-model',
      'tech-api',
      'tech-config',
      'backup-restore',
    ],
  },
] as const

export const DOC_SLUGS: readonly string[] = DOC_GROUPS.flatMap((group) => group.slugs)

export interface DocSection {
  id: string
  text: string
}

export interface Doc {
  slug: string
  title: string
  html: string
  sections: DocSection[]
}

export function anchorId(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

const md = new Marked({
  gfm: true,
  renderer: {
    heading(token: Tokens.Heading) {
      const body = this.parser.parseInline(token.tokens)
      return `<h${token.depth} id="${anchorId(token.text)}">${body}</h${token.depth}>\n`
    },
  },
})

function parse(slug: string, raw: string): Doc {
  const tokens = md.lexer(raw)
  const titleIndex = tokens.findIndex((t) => t.type === 'heading' && t.depth === 1)
  const title = titleIndex >= 0 ? (tokens[titleIndex] as Tokens.Heading).text : slug
  // The H1 becomes the page masthead, so drop it from the body.
  if (titleIndex >= 0) tokens.splice(titleIndex, 1)

  const sections = tokens
    .filter((t): t is Tokens.Heading => t.type === 'heading' && t.depth === 2)
    .map((t) => ({ id: anchorId(t.text), text: t.text }))

  return { slug, title, html: md.parser(tokens), sections }
}

// ponytail: content is bundled markdown we ship, not user input — the rendered
// HTML goes straight into the page without a sanitizer pass.
const files = import.meta.glob('../../content/docs/*/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

const byLang: Record<string, Record<string, Doc>> = {}
for (const [path, raw] of Object.entries(files)) {
  const match = path.match(/\/docs\/([^/]+)\/([^/]+)\.md$/)
  if (!match) continue
  const [, lang, slug] = match
  byLang[lang] ??= {}
  byLang[lang][slug] = parse(slug, raw)
}

/** Italian is the primary locale: anything missing in `lang` falls back to it. */
export function getDoc(slug: string | undefined, lang: string): Doc | undefined {
  if (!slug) return undefined
  return byLang[lang]?.[slug] ?? byLang.it?.[slug]
}

export function getDocs(lang: string): Doc[] {
  return DOC_SLUGS.map((slug) => getDoc(slug, lang)).filter((doc): doc is Doc => !!doc)
}

/** Same docs as getDocs, split into the sidebar's groups. Empty groups drop out,
 *  so a page that has not been written yet simply does not appear. */
export function getDocGroups(lang: string): { key: string; docs: Doc[] }[] {
  return DOC_GROUPS.map((group) => ({
    key: group.key,
    docs: group.slugs.map((slug) => getDoc(slug, lang)).filter((doc): doc is Doc => !!doc),
  })).filter((group) => group.docs.length > 0)
}

// account-errors.md uses prose headings, so a sync_error_code never slugifies
// into one. Map each code to its position on that page, which is identical in
// every locale. ponytail: positional — reordering the page shifts an anchor, it
// cannot break the link, because docHref falls back to the page top.
const SECTION_BY_CODE: Record<string, number> = {
  LWA_SECRET_EXPIRED: 0,
  MISSING_CREDENTIALS: 1,
  INVALID_MARKETPLACE: 2,
  AUTH_FAILED: 3,
  SellingApiForbiddenException: 3,
  SellingApiRequestThrottledException: 4,
  SellingApiServerException: 4,
  SellingApiTemporarilyUnavailableException: 4,
  seller_mismatch: 5,
  MISSING_ADVERTISING_PROFILE: 6,
}

/** Anchor only when the page really declares that section; a dead #hash would just no-op. */
export function docHref(slug: string, lang: string, anchor?: string | null): string {
  if (!anchor) return `/docs/${slug}`
  const sections = getDoc(slug, lang)?.sections ?? []
  const id = anchorId(anchor)
  const target =
    sections.find((section) => section.id === id) ?? sections[SECTION_BY_CODE[anchor] ?? -1]
  return `/docs/${slug}${target ? `#${target.id}` : ''}`
}
