"""Async forecast export package service."""
from __future__ import annotations

import io
import logging
import zipfile
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from typing import Any, Dict, List, Optional
from uuid import UUID

from openpyxl import Workbook
from sqlalchemy import func, select, text as sa_text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings
from app.models.amazon_account import AmazonAccount
from app.models.forecast import Forecast
from app.models.forecast_export_job import ForecastExportJob
from app.models.sales_data import SalesData
from app.schemas.analytics import ForecastHistoricalPoint
from app.services.ai_analysis_service import ForecastInsightsAnalysisService
from app.services.data_extraction import DAILY_TOTAL_ASIN
from app.services.excel_templates import ExcelTemplateRenderer, TEMPLATES
from app.services.forecast_pdf_service import ForecastInsightsPdfBuilder

logger = logging.getLogger(__name__)


TR = {
    "en": {
        "report_title": "Sales Forecast Report",
        "subtitle": "Generated by Inthezon Platform",
        "account": "Account",
        "product": "Product (ASIN)",
        "forecast_type": "Forecast Type",
        "generated_at": "Generated At",
        "forecast_model": "Forecast Model",
        "forecast_horizon": "Forecast Horizon",
        "confidence_level": "Confidence Level",
        "currency": "Currency",
        "mape": "MAPE",
        "rmse": "RMSE",
        "total_predicted": "Total Predicted Value",
        "avg_daily": "Average Daily Value",
        "peak_day": "Peak Day",
        "peak_value": "Peak Value",
        "summary_sheet": "Forecast Summary",
        "data_sheet": "Daily Forecast",
        "all_products": "All Products (Account-wide)",
        "days_suffix": "days",
        "date": "Date",
        "day_of_week": "Day",
        "predicted_value": "Predicted Value",
        "lower_bound": "Lower Bound 95%",
        "upper_bound": "Upper Bound 95%",
        "currency_col": "Currency",
        "section": "Section",
        "metric": "Metric",
        "value": "Value",
        "metadata": "Metadata",
        "model_metrics": "Model Metrics",
        "forecast_summary": "Summary",
        "type_labels": {"sales": "Sales Forecast", "units": "Units Forecast", "revenue": "Revenue Forecast"},
        "model_labels": {"prophet": "Prophet", "arima": "ARIMA", "xgboost": "XGBoost", "simple": "Simple"},
        "day_names": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    },
    "it": {
        "report_title": "Report Previsione Vendite",
        "subtitle": "Generato dalla piattaforma Inthezon",
        "account": "Account",
        "product": "Prodotto (ASIN)",
        "forecast_type": "Tipo Previsione",
        "generated_at": "Generato Il",
        "forecast_model": "Modello Previsione",
        "forecast_horizon": "Orizzonte Previsione",
        "confidence_level": "Livello di Confidenza",
        "currency": "Valuta",
        "mape": "MAPE",
        "rmse": "RMSE",
        "total_predicted": "Valore Totale Previsto",
        "avg_daily": "Valore Medio Giornaliero",
        "peak_day": "Giorno di Picco",
        "peak_value": "Valore di Picco",
        "summary_sheet": "Riepilogo Previsione",
        "data_sheet": "Previsione Giornaliera",
        "all_products": "Tutti i Prodotti (Intero Account)",
        "days_suffix": "giorni",
        "date": "Data",
        "day_of_week": "Giorno",
        "predicted_value": "Valore Previsto",
        "lower_bound": "Limite Inferiore 95%",
        "upper_bound": "Limite Superiore 95%",
        "currency_col": "Valuta",
        "section": "Sezione",
        "metric": "Metrica",
        "value": "Valore",
        "metadata": "Metadata",
        "model_metrics": "Metriche Modello",
        "forecast_summary": "Riepilogo",
        "type_labels": {"sales": "Previsione Vendite", "units": "Previsione Unità", "revenue": "Previsione Fatturato"},
        "model_labels": {"prophet": "Prophet", "arima": "ARIMA", "xgboost": "XGBoost", "simple": "Simple"},
        "day_names": ["Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica"],
    },
}


@dataclass
class ForecastExportContext:
    """Context bundle for a forecast export."""

    forecast: Forecast
    account_name: str
    language: str
    template: str
    historical: List[ForecastHistoricalPoint]


class ForecastExportService:
    """Service for creating and tracking async forecast export jobs."""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def create_job(
        self,
        *,
        org_id: UUID,
        user_id: UUID,
        forecast_id: UUID,
        template: str,
        language: str,
        include_insights: bool,
    ) -> ForecastExportJob:
        await self._get_forecast_context(
            org_id=org_id,
            forecast_id=forecast_id,
            template=template,
            language=language,
        )

        if include_insights and not settings.ANTHROPIC_API_KEY:
            raise ValueError("ANTHROPIC_API_KEY is not configured")

        job = ForecastExportJob(
            organization_id=org_id,
            created_by_id=user_id,
            forecast_id=forecast_id,
            template=template,
            language=language,
            include_insights=include_insights,
            status="pending",
            progress_step="Queued",
            progress_pct=0,
        )
        self.db.add(job)
        await self.db.flush()
        await self.db.refresh(job)
        return job

    async def get_job(self, job_id: UUID, org_id: UUID) -> Optional[ForecastExportJob]:
        result = await self.db.execute(
            select(ForecastExportJob).where(
                ForecastExportJob.id == job_id,
                ForecastExportJob.organization_id == org_id,
            )
        )
        return result.scalar_one_or_none()

    async def _get_forecast_context(
        self,
        *,
        org_id: UUID,
        forecast_id: UUID,
        template: str,
        language: str,
    ) -> ForecastExportContext:
        accounts_query = select(AmazonAccount.id).where(AmazonAccount.organization_id == org_id)
        result = await self.db.execute(
            select(Forecast, AmazonAccount.account_name)
            .join(AmazonAccount, Forecast.account_id == AmazonAccount.id)
            .where(
                Forecast.id == forecast_id,
                Forecast.account_id.in_(accounts_query),
            )
        )
        row = result.one_or_none()
        if not row:
            raise ValueError("Forecast not found")

        forecast, account_name = row
        historical = await self._fetch_historical(
            account_id=forecast.account_id,
            asin=forecast.asin,
        )
        return ForecastExportContext(
            forecast=forecast,
            account_name=account_name,
            language="it" if language == "it" else "en",
            template=template,
            historical=historical,
        )

    async def _fetch_historical(
        self,
        *,
        account_id: UUID,
        asin: Optional[str],
        days: int = 30,
    ) -> List[ForecastHistoricalPoint]:
        start_date = date.today() - timedelta(days=days)
        query = (
            select(SalesData.date, func.sum(SalesData.ordered_product_sales).label("value"))
            .where(SalesData.account_id == account_id, SalesData.date >= start_date)
            .group_by(SalesData.date)
            .order_by(SalesData.date)
        )
        query = query.where(SalesData.asin == (asin or DAILY_TOTAL_ASIN))
        result = await self.db.execute(query)
        return [
            ForecastHistoricalPoint(date=row.date, value=float(row.value or 0))
            for row in result.all()
        ]


def build_forecast_workbook_bytes(
    forecast: Forecast,
    account_name: str,
    *,
    template: str,
    language: str,
) -> bytes:
    """Build the Excel workbook bytes for a forecast export."""
    from datetime import datetime as dt

    lang = "it" if language == "it" else "en"
    style = TEMPLATES.get(template, TEMPLATES["corporate"])
    renderer = ExcelTemplateRenderer(style)
    t = TR[lang]

    predictions = forecast.predictions or []
    forecast_type = forecast.forecast_type or "sales"
    model_used = forecast.model_used or "prophet"
    horizon = forecast.forecast_horizon_days or 30
    ci = float(forecast.confidence_interval or 0.95)
    mape = float(forecast.mape) if forecast.mape is not None else None
    rmse = float(forecast.rmse) if forecast.rmse is not None else None

    values = [p["value"] for p in predictions]
    total = sum(values)
    avg_daily = total / len(values) if values else 0
    peak_idx = values.index(max(values)) if values else 0
    peak_pred = predictions[peak_idx] if predictions else None

    def _day_name(date_str: str) -> str:
        from datetime import date as d

        dt_obj = d.fromisoformat(date_str) if isinstance(date_str, str) else date_str
        return t["day_names"][dt_obj.weekday()]

    def _label(labels: dict, raw: str) -> str:
        return labels.get(raw, raw.capitalize())

    wb = Workbook()
    wb.remove(wb.active)

    ws_summary = wb.create_sheet(title=t["summary_sheet"][:31])
    generated_str = (
        forecast.generated_at.strftime("%Y-%m-%d %H:%M")
        if forecast.generated_at
        else dt.utcnow().strftime("%Y-%m-%d %H:%M")
    )
    next_row = renderer.write_title_banner(
        ws_summary,
        title=t["report_title"],
        subtitle=t["subtitle"],
        metadata_rows=[
            (t["account"], account_name),
            (t["product"], forecast.asin or t["all_products"]),
            (t["forecast_type"], _label(t["type_labels"], forecast_type)),
            (t["generated_at"], generated_str),
            (t["forecast_model"], _label(t["model_labels"], model_used)),
            (t["forecast_horizon"], f"{horizon} {t['days_suffix']}"),
            (t["confidence_level"], f"{int(ci * 100)}%"),
            (t["currency"], "EUR"),
        ],
    )

    summary_columns = ["section", "metric", "current_value"]
    summary_headers = [t["section"], t["metric"], t["value"]]
    summary_rows = [
        {"section": t["model_metrics"], "metric": t["mape"], "current_value": f"{mape:.2f}%" if mape is not None else "N/A"},
        {"section": t["model_metrics"], "metric": t["rmse"], "current_value": round(rmse, 2) if rmse is not None else "N/A"},
        {"section": t["forecast_summary"], "metric": t["total_predicted"], "current_value": round(total, 2)},
        {"section": t["forecast_summary"], "metric": t["avg_daily"], "current_value": round(avg_daily, 2)},
        {"section": t["forecast_summary"], "metric": t["peak_day"], "current_value": f"{peak_pred['date']} ({_day_name(peak_pred['date'])})" if peak_pred else "N/A"},
        {"section": t["forecast_summary"], "metric": t["peak_value"], "current_value": round(peak_pred["value"], 2) if peak_pred else "N/A"},
    ]
    renderer.write_summary_sheet(ws_summary, summary_rows, summary_columns, summary_headers, start_row=next_row)

    ws_data = wb.create_sheet(title=t["data_sheet"][:31])
    data_columns = ["date", "day_of_week", "predicted_value", "lower_bound", "upper_bound", "currency"]
    data_headers = [t["date"], t["day_of_week"], t["predicted_value"], t["lower_bound"], t["upper_bound"], t["currency_col"]]
    data_rows = []
    for p in predictions:
        pred_date = p["date"]
        data_rows.append({
            "date": pred_date if isinstance(pred_date, str) else pred_date.isoformat(),
            "day_of_week": _day_name(pred_date),
            "predicted_value": round(p["value"], 2),
            "lower_bound": round(p.get("lower", p["value"] * 0.8), 2),
            "upper_bound": round(p.get("upper", p["value"] * 1.2), 2),
            "currency": "EUR",
        })
    renderer.write_data_sheet(ws_data, data_rows, data_columns, data_headers)

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output.getvalue()


def build_forecast_excel_filename(
    forecast: Forecast,
    account_name: str,
    *,
    template: str,
    language: str,
) -> str:
    """Build the standalone Excel filename for a forecast export."""
    style = TEMPLATES.get(template, TEMPLATES["corporate"])
    safe_name = account_name.replace(" ", "_")[:30]
    forecast_type = forecast.forecast_type or "sales"
    horizon = forecast.forecast_horizon_days or 30
    today = date.today().isoformat()
    lang = "it" if language == "it" else "en"
    return f"inthezon_forecast_{safe_name}_{forecast_type}_{horizon}d_{style.name}_{today}_{lang}.xlsx"


def _build_metrics(forecast: Forecast) -> Dict[str, Optional[float | str]]:
    predictions = forecast.predictions or []
    values = [p["value"] for p in predictions]
    total = sum(values)
    avg_daily = total / len(values) if values else 0
    peak_idx = values.index(max(values)) if values else 0
    peak_pred = predictions[peak_idx] if predictions else None
    return {
        "total_predicted": round(total, 2),
        "avg_daily": round(avg_daily, 2),
        "peak_day": peak_pred["date"] if peak_pred else None,
        "peak_value": round(peak_pred["value"], 2) if peak_pred else None,
        "mape": float(forecast.mape) if forecast.mape is not None else None,
        "rmse": float(forecast.rmse) if forecast.rmse is not None else None,
    }


def _build_ai_payload(context: ForecastExportContext) -> Dict[str, Any]:
    forecast = context.forecast
    predictions = forecast.predictions or []
    historical = [
        {"date": point.date.isoformat(), "value": point.value}
        for point in context.historical
    ]
    return {
        "account_name": context.account_name,
        "asin": forecast.asin,
        "forecast_type": forecast.forecast_type or "sales",
        "model_used": forecast.model_used or "prophet",
        "horizon_days": forecast.forecast_horizon_days or 30,
        "confidence_interval": float(forecast.confidence_interval or 0.95),
        "generated_at": forecast.generated_at.isoformat() if forecast.generated_at else None,
        "metrics": _build_metrics(forecast),
        "historical_data": historical,
        "predictions": predictions,
    }


def _build_package_filename(context: ForecastExportContext) -> str:
    safe_name = context.account_name.replace(" ", "_")[:30]
    forecast_type = context.forecast.forecast_type or "sales"
    horizon = context.forecast.forecast_horizon_days or 30
    today = date.today().isoformat()
    return f"inthezon_forecast_package_{safe_name}_{forecast_type}_{horizon}d_{today}.zip"


def process_forecast_export_job(job_id: str):
    """Process a forecast export job in a background worker or thread."""
    from app.db.session import db_url as _db_url

    _local_engine = create_async_engine(
        _db_url,
        echo=settings.APP_DEBUG,
        pool_size=2,
        max_overflow=1,
    )
    _LocalSession = async_sessionmaker(
        bind=_local_engine,
        class_=AsyncSession,
        expire_on_commit=False,
        autoflush=False,
    )

    async def _set_progress(step: str, pct: int):
        try:
            async with _LocalSession() as pdb:
                await pdb.execute(
                    sa_text(
                        "UPDATE forecast_export_jobs "
                        "SET progress_step = :step, progress_pct = :pct "
                        "WHERE id = :rid"
                    ),
                    {"step": step, "pct": pct, "rid": job_id},
                )
                await pdb.commit()
        except Exception as exc:
            logger.warning("Forecast export progress update failed for %s: %s", job_id, exc)

    async def _process():
        async with _LocalSession() as db:
            service = ForecastExportService(db)
            result = await db.execute(select(ForecastExportJob).where(ForecastExportJob.id == UUID(job_id)))
            job = result.scalar_one_or_none()
            if not job:
                logger.error("Forecast export job %s not found", job_id)
                return

            try:
                job.status = "processing"
                await db.commit()
                await _set_progress("Preparing export...", 10)

                context = await service._get_forecast_context(
                    org_id=job.organization_id,
                    forecast_id=job.forecast_id,
                    template=job.template,
                    language=job.language,
                )

                await _set_progress("Generating forecast workbook...", 35)
                workbook_bytes = build_forecast_workbook_bytes(
                    context.forecast,
                    context.account_name,
                    template=job.template,
                    language=job.language,
                )

                pdf_bytes = None
                if job.include_insights:
                    if not settings.ANTHROPIC_API_KEY:
                        raise ValueError("ANTHROPIC_API_KEY is not configured")

                    await _set_progress("Generating AI insights...", 70)
                    ai_service = ForecastInsightsAnalysisService(settings.ANTHROPIC_API_KEY)
                    analysis = ai_service.analyze(
                        forecast_data=_build_ai_payload(context),
                        language=job.language,
                    )

                    await _set_progress("Creating PDF report...", 85)
                    title = "Forecast Insights Report" if job.language != "it" else "Report Insight Forecast"
                    pdf_bytes = ForecastInsightsPdfBuilder(
                        title=title,
                        account_name=context.account_name,
                        asin=context.forecast.asin,
                        forecast_type=context.forecast.forecast_type or "sales",
                        model_used=context.forecast.model_used or "prophet",
                        horizon_days=context.forecast.forecast_horizon_days or 30,
                        confidence_interval=float(context.forecast.confidence_interval or 0.95),
                        generated_at=context.forecast.generated_at,
                        metrics=_build_metrics(context.forecast),
                        analysis=analysis,
                        language=job.language,
                    ).build()

                await _set_progress("Packaging files...", 95)
                archive = io.BytesIO()
                with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as zip_file:
                    zip_file.writestr("forecast.xlsx", workbook_bytes)
                    if pdf_bytes is not None:
                        zip_file.writestr("insights.pdf", pdf_bytes)

                job.artifact_data = archive.getvalue()
                job.artifact_filename = _build_package_filename(context)
                job.artifact_content_type = "application/zip"
                job.status = "completed"
                job.progress_step = "Complete"
                job.progress_pct = 100
                job.completed_at = datetime.utcnow()
                job.error_message = None
                await db.commit()
            except Exception as exc:
                logger.exception("Forecast export job %s failed", job_id)
                await db.rollback()
                async with _LocalSession() as fdb:
                    fail_result = await fdb.execute(select(ForecastExportJob).where(ForecastExportJob.id == UUID(job_id)))
                    failed_job = fail_result.scalar_one_or_none()
                    if failed_job:
                        failed_job.status = "failed"
                        failed_job.error_message = str(exc)[:500]
                        failed_job.progress_step = "Failed"
                        failed_job.completed_at = datetime.utcnow()
                        await fdb.commit()

    import asyncio

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(_process())
    finally:
        loop.run_until_complete(_local_engine.dispose())
        loop.close()
