"""Translation strings for Market Research PDF reports."""
from __future__ import annotations

from typing import Literal

Language = Literal["en", "it"]

PDF_TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        # Cover
        "cover_brand": "Inthezon",
        "cover_tagline": "Amazon Market Intelligence",
        "cover_product_analysis": "Product Analysis",
        "cover_market_tracker": "Market Tracker 360",
        "cover_marketplace": "Marketplace",
        "cover_generated": "Generated",
        "cover_source_asin": "Source ASIN",
        "cover_search_query": "Search Query",
        "cover_language": "Language",
        "cover_confidential": "Confidential",

        # Executive Summary
        "exec_title": "Executive Summary",
        "exec_overall_score": "Overall Score",
        "exec_ai_summary": "AI Analysis Summary",
        "exec_market_overview": "Market Overview",
        "exec_market_position": "Market Position",
        "exec_total_products": "Total Products",
        "exec_avg_price": "Average Price",
        "exec_price_range": "Range",
        "exec_avg_bsr": "Average BSR",
        "exec_unique_brands": "Unique Brands",
        "exec_vs_market_avg": "vs Market Average",
        "exec_price": "Price",
        "exec_bsr": "BSR",
        "exec_reviews": "Reviews",
        "exec_rating": "Rating",
        "exec_above_avg": "above avg",
        "exec_below_avg": "below avg",
        "exec_at_avg": "at average",
        "exec_no_data": "N/A",

        # Charts
        "charts_title": "Market Visualization",
        "charts_price_dist": "Price Distribution",
        "charts_price_dist_caption": "Distribution of product prices across the market sample.",
        "charts_bsr_position": "BSR vs Price Position",
        "charts_bsr_caption": "Each point represents a product. Lower BSR = higher sales rank.",
        "charts_radar": "Competitive Radar",
        "charts_radar_caption": "Multi-dimensional comparison: your product vs competitor average.",

        # Comparison
        "comp_title": "Competitive Comparison",
        "comp_asin": "ASIN",
        "comp_product": "Product",
        "comp_price": "Price",
        "comp_bsr": "BSR",
        "comp_reviews": "Reviews",
        "comp_rating": "Rating",
        "comp_your_product": "YOUR PRODUCT",
        "comp_competitors_analyzed": "competitors analyzed",
        "comp_reference_product": "Reference Product",

        # AI Analysis
        "ai_title": "AI-Powered Analysis",
        "ai_strengths": "Strengths",
        "ai_weaknesses": "Weaknesses",
        "ai_recommendations": "Recommendations",
        "ai_rec_area": "Area",
        "ai_rec_priority": "Priority",
        "ai_rec_action": "Action",
        "ai_rec_impact": "Expected Impact",
        "ai_priority_high": "HIGH",
        "ai_priority_medium": "MEDIUM",
        "ai_priority_low": "LOW",
        "ai_no_analysis": "AI analysis was not generated for this report.",

        # Footer
        "footer_confidential": "Confidential",
        "footer_generated_by": "Generated by Inthezon",
        "footer_page": "Page",
    },
    "it": {
        # Cover
        "cover_brand": "Inthezon",
        "cover_tagline": "Amazon Market Intelligence",
        "cover_product_analysis": "Analisi Prodotto",
        "cover_market_tracker": "Market Tracker 360",
        "cover_marketplace": "Marketplace",
        "cover_generated": "Generato il",
        "cover_source_asin": "ASIN Sorgente",
        "cover_search_query": "Ricerca",
        "cover_language": "Lingua",
        "cover_confidential": "Riservato",

        # Executive Summary
        "exec_title": "Riepilogo Esecutivo",
        "exec_overall_score": "Punteggio Complessivo",
        "exec_ai_summary": "Sintesi dell'Analisi AI",
        "exec_market_overview": "Panoramica del Mercato",
        "exec_market_position": "Posizione di Mercato",
        "exec_total_products": "Prodotti Totali",
        "exec_avg_price": "Prezzo Medio",
        "exec_price_range": "Range",
        "exec_avg_bsr": "BSR Medio",
        "exec_unique_brands": "Brand Unici",
        "exec_vs_market_avg": "vs Media di Mercato",
        "exec_price": "Prezzo",
        "exec_bsr": "BSR",
        "exec_reviews": "Recensioni",
        "exec_rating": "Valutazione",
        "exec_above_avg": "sopra la media",
        "exec_below_avg": "sotto la media",
        "exec_at_avg": "nella media",
        "exec_no_data": "N/D",

        # Charts
        "charts_title": "Visualizzazione del Mercato",
        "charts_price_dist": "Distribuzione Prezzi",
        "charts_price_dist_caption": "Distribuzione dei prezzi dei prodotti nel campione di mercato.",
        "charts_bsr_position": "Posizione BSR vs Prezzo",
        "charts_bsr_caption": "Ogni punto rappresenta un prodotto. BSR inferiore = posizione di vendita migliore.",
        "charts_radar": "Radar Competitivo",
        "charts_radar_caption": "Confronto multidimensionale: il tuo prodotto vs la media dei competitor.",

        # Comparison
        "comp_title": "Confronto Competitivo",
        "comp_asin": "ASIN",
        "comp_product": "Prodotto",
        "comp_price": "Prezzo",
        "comp_bsr": "BSR",
        "comp_reviews": "Recensioni",
        "comp_rating": "Valutazione",
        "comp_your_product": "IL TUO PRODOTTO",
        "comp_competitors_analyzed": "competitor analizzati",
        "comp_reference_product": "Prodotto di Riferimento",

        # AI Analysis
        "ai_title": "Analisi Basata su AI",
        "ai_strengths": "Punti di Forza",
        "ai_weaknesses": "Punti di Debolezza",
        "ai_recommendations": "Raccomandazioni",
        "ai_rec_area": "Area",
        "ai_rec_priority": "Priorit\u00e0",
        "ai_rec_action": "Azione",
        "ai_rec_impact": "Impatto Atteso",
        "ai_priority_high": "ALTA",
        "ai_priority_medium": "MEDIA",
        "ai_priority_low": "BASSA",
        "ai_no_analysis": "L'analisi AI non \u00e8 stata generata per questo report.",

        # Footer
        "footer_confidential": "Riservato",
        "footer_generated_by": "Generato da Inthezon",
        "footer_page": "Pagina",
    },
}


def t(key: str, lang: Language = "en") -> str:
    """Get translated string for the given key and language."""
    return PDF_TRANSLATIONS.get(lang, PDF_TRANSLATIONS["en"]).get(
        key, PDF_TRANSLATIONS["en"].get(key, key)
    )
