"""XLSX export for strategic recommendations (US-7.5).

Produces a client-facing report from a set of stored strategic
recommendations. Includes a metadata banner with the requested scope and
a per-recommendation breakdown so the user can hand the deliverable to a
stakeholder without having to re-explain what the AI suggested.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Iterable, Optional

from openpyxl import Workbook

from app.models.strategic_recommendation import StrategicRecommendation
from app.services.excel_templates import TEMPLATES, ExcelTemplateRenderer


TR = {
    "en": {
        "report_title": "Strategic Recommendations Report",
        "subtitle": "Generated by Inthezon Platform",
        "scope": "Scope",
        "account": "Account",
        "asin": "ASIN",
        "all_accounts": "All accounts",
        "all_products": "All products",
        "generated_at": "Generated at",
        "total": "Recommendations",
        "summary_sheet": "Summary",
        "details_sheet": "Recommendations",
        "category": "Category",
        "priority": "Priority",
        "confidence": "Confidence",
        "title": "Title",
        "rationale": "Rationale",
        "expected_impact": "Expected impact",
        "scope_account": "Account scope",
        "scope_asin": "ASIN scope",
        "generated": "Generated",
        "status": "Status",
        "no_value": "—",
        "by_category": "By category",
        "by_priority": "By priority",
        "section": "Section",
        "metric": "Metric",
        "value": "Value",
    },
    "it": {
        "report_title": "Report Raccomandazioni Strategiche",
        "subtitle": "Generato dalla piattaforma Inthezon",
        "scope": "Ambito",
        "account": "Account",
        "asin": "ASIN",
        "all_accounts": "Tutti gli account",
        "all_products": "Tutti i prodotti",
        "generated_at": "Generato il",
        "total": "Raccomandazioni",
        "summary_sheet": "Riepilogo",
        "details_sheet": "Raccomandazioni",
        "category": "Categoria",
        "priority": "Priorità",
        "confidence": "Affidabilità",
        "title": "Titolo",
        "rationale": "Motivazione",
        "expected_impact": "Impatto atteso",
        "scope_account": "Ambito account",
        "scope_asin": "Ambito ASIN",
        "generated": "Generata",
        "status": "Stato",
        "no_value": "—",
        "by_category": "Per categoria",
        "by_priority": "Per priorità",
        "section": "Sezione",
        "metric": "Metrica",
        "value": "Valore",
    },
}

STATUS_LABELS = {
    "en": {"pending": "Pending", "implemented": "Implemented", "dismissed": "Dismissed"},
    "it": {"pending": "In sospeso", "implemented": "Implementata", "dismissed": "Scartata"},
}

CONFIDENCE_LABELS = {
    "en": {"high": "High", "medium": "Medium", "low": "Low"},
    "it": {"high": "Alta", "medium": "Media", "low": "Bassa"},
}

CATEGORY_LABELS = {
    "en": {
        "pricing": "Pricing",
        "advertising": "Advertising",
        "inventory": "Inventory",
        "content": "Content",
    },
    "it": {
        "pricing": "Prezzi",
        "advertising": "Pubblicità",
        "inventory": "Inventario",
        "content": "Contenuti",
    },
}

PRIORITY_LABELS = {
    "en": {"high": "High", "medium": "Medium", "low": "Low"},
    "it": {"high": "Alta", "medium": "Media", "low": "Bassa"},
}


def _scoped_asin(rec: StrategicRecommendation) -> Optional[str]:
    context = rec.context if isinstance(rec.context, dict) else None
    if not context:
        return None
    asins = context.get("asins")
    if isinstance(asins, list):
        for value in asins:
            if isinstance(value, str) and value:
                return value
    filters = context.get("generation_filters")
    if isinstance(filters, dict):
        raw = filters.get("asin")
        if isinstance(raw, str) and raw:
            return raw
    return None


def _scoped_account_id(rec: StrategicRecommendation) -> Optional[str]:
    if rec.account_id is not None:
        return str(rec.account_id)
    context = rec.context if isinstance(rec.context, dict) else None
    if not context:
        return None
    raw = context.get("account_id")
    if isinstance(raw, str) and raw:
        return raw
    filters = context.get("generation_filters")
    if isinstance(filters, dict):
        raw = filters.get("account_id")
        if isinstance(raw, str) and raw:
            return raw
    return None


def build_recommendations_workbook_bytes(
    recommendations: Iterable[StrategicRecommendation],
    *,
    account_names: dict[str, str],
    language: str = "en",
    scope_account_id: Optional[str] = None,
    scope_asin: Optional[str] = None,
    template: str = "corporate",
) -> bytes:
    """Build a styled XLSX workbook for a set of strategic recommendations."""
    lang = "it" if language == "it" else "en"
    style = TEMPLATES.get(template, TEMPLATES["corporate"])
    renderer = ExcelTemplateRenderer(style)
    t = TR[lang]
    cat_labels = CATEGORY_LABELS[lang]
    pri_labels = PRIORITY_LABELS[lang]
    status_labels = STATUS_LABELS[lang]
    conf_labels = CONFIDENCE_LABELS[lang]

    items = list(recommendations)

    wb = Workbook()
    wb.remove(wb.active)

    ws_summary = wb.create_sheet(title=t["summary_sheet"][:31])
    account_label = (
        account_names.get(scope_account_id, scope_account_id)
        if scope_account_id
        else t["all_accounts"]
    )
    asin_label = scope_asin or t["all_products"]
    next_row = renderer.write_title_banner(
        ws_summary,
        title=t["report_title"],
        subtitle=t["subtitle"],
        metadata_rows=[
            (t["scope_account"], account_label),
            (t["scope_asin"], asin_label),
            (t["generated_at"], datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")),
            (t["total"], str(len(items))),
        ],
    )

    by_category: dict[str, int] = {}
    by_priority: dict[str, int] = {}
    for rec in items:
        by_category[rec.category] = by_category.get(rec.category, 0) + 1
        by_priority[rec.priority] = by_priority.get(rec.priority, 0) + 1

    summary_rows = []
    for cat, count in sorted(by_category.items(), key=lambda kv: -kv[1]):
        summary_rows.append(
            {
                "section": t["by_category"],
                "metric": cat_labels.get(cat, cat),
                "value": count,
            }
        )
    for pri in ("high", "medium", "low"):
        if pri in by_priority:
            summary_rows.append(
                {
                    "section": t["by_priority"],
                    "metric": pri_labels.get(pri, pri),
                    "value": by_priority[pri],
                }
            )

    renderer.write_summary_sheet(
        ws_summary,
        summary_rows,
        ["section", "metric", "value"],
        [t["section"], t["metric"], t["value"]],
        start_row=next_row,
    )

    ws_details = wb.create_sheet(title=t["details_sheet"][:31])
    detail_columns = [
        "category",
        "priority",
        "confidence",
        "title",
        "rationale",
        "expected_impact",
        "scope_account",
        "scope_asin",
        "status",
        "generated",
    ]
    detail_headers = [
        t["category"],
        t["priority"],
        t["confidence"],
        t["title"],
        t["rationale"],
        t["expected_impact"],
        t["scope_account"],
        t["scope_asin"],
        t["status"],
        t["generated"],
    ]
    detail_rows = []
    for rec in items:
        account_id = _scoped_account_id(rec)
        scoped_account_label = (
            account_names.get(account_id, account_id)
            if account_id
            else t["all_accounts"]
        )
        scoped_asin_label = _scoped_asin(rec) or t["all_products"]
        detail_rows.append(
            {
                "category": cat_labels.get(rec.category, rec.category),
                "priority": pri_labels.get(rec.priority, rec.priority),
                "confidence": conf_labels.get(
                    getattr(rec, "confidence", "medium"),
                    getattr(rec, "confidence", "medium"),
                ),
                "title": rec.title,
                "rationale": rec.rationale,
                "expected_impact": rec.expected_impact or t["no_value"],
                "scope_account": scoped_account_label,
                "scope_asin": scoped_asin_label,
                "status": status_labels.get(rec.status, rec.status),
                "generated": (
                    rec.generated_at.strftime("%Y-%m-%d %H:%M")
                    if rec.generated_at
                    else t["no_value"]
                ),
            }
        )
    renderer.write_data_sheet(ws_details, detail_rows, detail_columns, detail_headers)

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output.getvalue()
